/**
 * This class is generated by jOOQ
 */
package com.nextcont.ecm.fileengine.persistence.jooq.tables.records;


import com.nextcont.ecm.fileengine.persistence.jooq.tables.Meqaupload;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeqauploadRecord extends UpdatableRecordImpl<MeqauploadRecord> implements Record9<String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = -749761933;

	/**
	 * Setter for <code>ecm.meqaupload.globalId</code>.
	 */
	public void setGlobalid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ecm.meqaupload.globalId</code>.
	 */
	public String getGlobalid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ecm.meqaupload.filename</code>.
	 */
	public void setFilename(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ecm.meqaupload.filename</code>.
	 */
	public String getFilename() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ecm.meqaupload.mimetype</code>.
	 */
	public void setMimetype(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ecm.meqaupload.mimetype</code>.
	 */
	public String getMimetype() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ecm.meqaupload.contentlength</code>.
	 */
	public void setContentlength(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ecm.meqaupload.contentlength</code>.
	 */
	public Integer getContentlength() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>ecm.meqaupload.shardsize</code>.
	 */
	public void setShardsize(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ecm.meqaupload.shardsize</code>.
	 */
	public Integer getShardsize() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>ecm.meqaupload.createtime</code>.
	 */
	public void setCreatetime(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ecm.meqaupload.createtime</code>.
	 */
	public Timestamp getCreatetime() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>ecm.meqaupload.updatetime</code>.
	 */
	public void setUpdatetime(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ecm.meqaupload.updatetime</code>.
	 */
	public Timestamp getUpdatetime() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>ecm.meqaupload.currentshard</code>.
	 */
	public void setCurrentshard(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ecm.meqaupload.currentshard</code>.
	 */
	public Integer getCurrentshard() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>ecm.meqaupload.partfilesize</code>.
	 */
	public void setPartfilesize(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ecm.meqaupload.partfilesize</code>.
	 */
	public Integer getPartfilesize() {
		return (Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Meqaupload.MEQAUPLOAD.GLOBALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Meqaupload.MEQAUPLOAD.FILENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Meqaupload.MEQAUPLOAD.MIMETYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Meqaupload.MEQAUPLOAD.CONTENTLENGTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Meqaupload.MEQAUPLOAD.SHARDSIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Meqaupload.MEQAUPLOAD.CREATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Meqaupload.MEQAUPLOAD.UPDATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Meqaupload.MEQAUPLOAD.CURRENTSHARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Meqaupload.MEQAUPLOAD.PARTFILESIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getGlobalid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFilename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getMimetype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getContentlength();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getShardsize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getCreatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getUpdatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getCurrentshard();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getPartfilesize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord value1(String value) {
		setGlobalid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord value2(String value) {
		setFilename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord value3(String value) {
		setMimetype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord value4(Integer value) {
		setContentlength(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord value5(Integer value) {
		setShardsize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord value6(Timestamp value) {
		setCreatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord value7(Timestamp value) {
		setUpdatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord value8(Integer value) {
		setCurrentshard(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord value9(Integer value) {
		setPartfilesize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MeqauploadRecord values(String value1, String value2, String value3, Integer value4, Integer value5, Timestamp value6, Timestamp value7, Integer value8, Integer value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MeqauploadRecord
	 */
	public MeqauploadRecord() {
		super(Meqaupload.MEQAUPLOAD);
	}

	/**
	 * Create a detached, initialised MeqauploadRecord
	 */
	public MeqauploadRecord(String globalid, String filename, String mimetype, Integer contentlength, Integer shardsize, Timestamp createtime, Timestamp updatetime, Integer currentshard, Integer partfilesize) {
		super(Meqaupload.MEQAUPLOAD);

		setValue(0, globalid);
		setValue(1, filename);
		setValue(2, mimetype);
		setValue(3, contentlength);
		setValue(4, shardsize);
		setValue(5, createtime);
		setValue(6, updatetime);
		setValue(7, currentshard);
		setValue(8, partfilesize);
	}
}
