/**
 * This class is generated by jOOQ
 */
package com.nextcont.ecm.fileengine.persistence.jooq.tables.records;


import com.nextcont.ecm.fileengine.persistence.jooq.tables.TransitionCallback;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransitionCallbackRecord extends TableRecordImpl<TransitionCallbackRecord> implements Record5<String, String, String, String, Timestamp> {

	private static final long serialVersionUID = -1782239199;

	/**
	 * Setter for <code>ecm.transition_callback.globalId</code>.
	 */
	public void setGlobalid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ecm.transition_callback.globalId</code>.
	 */
	public String getGlobalid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ecm.transition_callback.status</code>.
	 */
	public void setStatus(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ecm.transition_callback.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ecm.transition_callback.info</code>.
	 */
	public void setInfo(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ecm.transition_callback.info</code>.
	 */
	public String getInfo() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ecm.transition_callback.callbackUrl</code>.
	 */
	public void setCallbackurl(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ecm.transition_callback.callbackUrl</code>.
	 */
	public String getCallbackurl() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ecm.transition_callback.createTime</code>.
	 */
	public void setCreatetime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ecm.transition_callback.createTime</code>.
	 */
	public Timestamp getCreatetime() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, String, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, String, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TransitionCallback.TRANSITION_CALLBACK.GLOBALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TransitionCallback.TRANSITION_CALLBACK.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TransitionCallback.TRANSITION_CALLBACK.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TransitionCallback.TRANSITION_CALLBACK.CALLBACKURL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return TransitionCallback.TRANSITION_CALLBACK.CREATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getGlobalid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getCallbackurl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getCreatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransitionCallbackRecord value1(String value) {
		setGlobalid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransitionCallbackRecord value2(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransitionCallbackRecord value3(String value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransitionCallbackRecord value4(String value) {
		setCallbackurl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransitionCallbackRecord value5(Timestamp value) {
		setCreatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransitionCallbackRecord values(String value1, String value2, String value3, String value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TransitionCallbackRecord
	 */
	public TransitionCallbackRecord() {
		super(TransitionCallback.TRANSITION_CALLBACK);
	}

	/**
	 * Create a detached, initialised TransitionCallbackRecord
	 */
	public TransitionCallbackRecord(String globalid, String status, String info, String callbackurl, Timestamp createtime) {
		super(TransitionCallback.TRANSITION_CALLBACK);

		setValue(0, globalid);
		setValue(1, status);
		setValue(2, info);
		setValue(3, callbackurl);
		setValue(4, createtime);
	}
}
