/**
 * This class is generated by jOOQ
 */
package com.nextcont.ecm.fileengine.persistence.jooq;


import com.nextcont.ecm.fileengine.persistence.jooq.tables.FastdfsFilerecord;
import com.nextcont.ecm.fileengine.persistence.jooq.tables.Meqaupload;
import com.nextcont.ecm.fileengine.persistence.jooq.tables.Transition;
import com.nextcont.ecm.fileengine.persistence.jooq.tables.TransitionCallback;
import com.nextcont.ecm.fileengine.persistence.jooq.tables.TransitionFile;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ecm extends SchemaImpl {

	private static final long serialVersionUID = -1028145018;

	/**
	 * The reference instance of <code>ecm</code>
	 */
	public static final Ecm ECM = new Ecm();

	/**
	 * No further instances allowed
	 */
	private Ecm() {
		super("ecm");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			FastdfsFilerecord.FASTDFS_FILERECORD,
			Meqaupload.MEQAUPLOAD,
			Transition.TRANSITION,
			TransitionCallback.TRANSITION_CALLBACK,
			TransitionFile.TRANSITION_FILE);
	}
}
