/**
 * This class is generated by jOOQ
 */
package com.nextcont.ecm.fileengine.persistence.jooq;


import com.nextcont.ecm.fileengine.persistence.jooq.tables.FastdfsFilerecord;
import com.nextcont.ecm.fileengine.persistence.jooq.tables.Meqaupload;
import com.nextcont.ecm.fileengine.persistence.jooq.tables.Transition;
import com.nextcont.ecm.fileengine.persistence.jooq.tables.TransitionCallback;
import com.nextcont.ecm.fileengine.persistence.jooq.tables.TransitionFile;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ecm
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table ecm.fastdfs_fileRecord
	 */
	public static final FastdfsFilerecord FASTDFS_FILERECORD = com.nextcont.ecm.fileengine.persistence.jooq.tables.FastdfsFilerecord.FASTDFS_FILERECORD;

	/**
	 * The table ecm.meqaupload
	 */
	public static final Meqaupload MEQAUPLOAD = com.nextcont.ecm.fileengine.persistence.jooq.tables.Meqaupload.MEQAUPLOAD;

	/**
	 * The table ecm.transition
	 */
	public static final Transition TRANSITION = com.nextcont.ecm.fileengine.persistence.jooq.tables.Transition.TRANSITION;

	/**
	 * The table ecm.transition_callback
	 */
	public static final TransitionCallback TRANSITION_CALLBACK = com.nextcont.ecm.fileengine.persistence.jooq.tables.TransitionCallback.TRANSITION_CALLBACK;

	/**
	 * The table ecm.transition_file
	 */
	public static final TransitionFile TRANSITION_FILE = com.nextcont.ecm.fileengine.persistence.jooq.tables.TransitionFile.TRANSITION_FILE;
}
